### ISSUE TITLE
why rayon spawn over tokio spawn

### ISSUE THREAD

**Issue by FU3X** [0bishop/Rusty-Stealer#1]

**Comment by FU3X** [comment]
also why goldberg stmt over obf stmt?

**Comment by 0bishop** [comment]
Cause i was stupid when i made it for the rayon, and i didnt have time to fix it.
for the goldberg its for having 2 layer obfuscation

if u want to fix it and making a merge request

**Comment by FU3X** [comment]
also @0bishop what resources did you use to find out about this?
```$env:RUSTFLAGS = "-Zlocation-detail=none -Ctarget-cpu=native -Cdebuginfo=0 -Zstrip=symbols -Zstrip=debuginfo --remap-path-prefix  C:\Users\$env:USERNAME\.cargo\registry\src\=caca"
cargo build --release```

**Comment by louislafosse** [comment]
MIT documentation.
https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/unstable-book/compiler-flags/remap-path-prefix.html

Those are optimisation flags and for striping strings in the binary

**Comment by 0bishop** [comment]
> also @0bishop what resources did you use to find out about this?
> 
> $env:RUSTFLAGS = "-Zlocation-detail=none -Ctarget-cpu=native -Cdebuginfo=0 -Zstrip=symbols -Zstrip=debuginfo --remap-path-prefix C:\Users$env:USERNAME.cargo\registry\src=caca" cargo build --release

Those are optimisation flags and string striping in the binary in order to hide pc name in .rdata section.

https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/unstable-book/compiler-flags/remap-path-prefix.html
